-- 01 Setup: warehouse, resource monitor, database and schemas (hospital account)
CREATE RESOURCE MONITOR IF NOT EXISTS FFU_RM WITH CREDIT_QUOTA = 10 FREQUENCY = DAILY
  START_TIMESTAMP = IMMEDIATELY TRIGGERS ON 80 PERCENT DO NOTIFY ON 100 PERCENT DO SUSPEND;
ALTER WAREHOUSE COMPUTE_WH SET WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 RESOURCE_MONITOR = FFU_RM;

CREATE DATABASE IF NOT EXISTS FFU;
CREATE SCHEMA IF NOT EXISTS FFU.RAW;   -- landed source data
CREATE SCHEMA IF NOT EXISTS FFU.KEY;   -- hidden answer key (eval only)
CREATE SCHEMA IF NOT EXISTS FFU.AI;    -- cached AI outputs
CREATE SCHEMA IF NOT EXISTS FFU.CORE;  -- rules, UDFs, dynamic tables
CREATE SCHEMA IF NOT EXISTS FFU.CTRL;  -- control tables (SIM_DATE)
CREATE SCHEMA IF NOT EXISTS FFU.APP;   -- app tables, search, agent, streamlit
CREATE SCHEMA IF NOT EXISTS FFU.SEC;   -- role-aware secure views
CREATE SCHEMA IF NOT EXISTS FFU.EVAL;  -- evaluation results
